CAK3DBOT
    src
        Commands
            Database
                database.js
                ping.js
                time.js
            Inventory
                add-item.js
                deduct.js
                delete-item.js
                order.js
                request.js
                view-inventory.js
                view-requests.js
            Nitrado
                link-log.js
                logs.js
                restart.js
                status.js
                unlink-log.js
            Socials
                disbutton.js
                fbbutton.js
                patbutton.js
                paybutton.js
                xbutton.js
            Tools
                embed.js
                menu.js
                modal.js
                react.js
            Users
                auto-complete.js
                await-react.js
                custom-status.js
                getAvatar.js
                link-name.js
                permissions.js
        Components
            Buttons
                Inventory
                    confirmation.js
                    delete-item-Selection.js
                    pagination.js
                Socials
                    sub-dis.js
                    sub-fb.js
                    sub-pat.js
                    sub-pay.js
                    sub-x.js
            Modals
                fav-color.js
                inputModal.js
            SelectMenus
                actionMenu.js 
                sub-menu.js
            Configuration
                servers.js
        Events
            client
                interactionCreate.js
                ready.js
            mongo
                connected.js
                connecting.js
                disconnected.js
                error.js
        Functions
            Handlers
                handleCommands.js
                handleComponents.js
                handleEvents.js
            Logs
                logEventHandler.js
            Tools
                pickPresence.js
            Utility
                nitrado.js
                NitradoAPI.js
        Schemas
            guild.js
            InventoryIyem.js
            StockRequest.js
        bot.js
    .env
    .gitignore
    CAK3DBOT.js
    package-lock.json
    package.json
    Procfile
